#!/bin/bash


echo Installing pacman-essentials...
echo batch installing  and building fish,jq,aria2,neovim,micro,lsd,kvantum and xfce4-screenshooter...
sudo pacman -Sy fish jq aria2 neovim micro lsd xfce4-screenshooter xfce4-taskmanager  kvantum-qt5 --noconfirm
echo pacman-essentials have been installed...

echo
echo Installing aur-essentials...
echo batch installing and building nerdfetch,ytop-bin,visual-studio-code-bin,librewolf-bin and ulauncher
yes y | paru -Syu nerdfetch ytop-bin visual-studio-code-bin librewolf-bin ulauncher --batchinstall --skipreview --removemake
echo aur-essentials have been installed...

echo
echo removing unused build packages...
yes y | paru -c
echo clearing uninstalled pkg cache...
sudo pacman -Sc --noconfirm
echo all essentials packages have been installed...
