#!/bin/bash

echo configuring Visual Studio Code...
echo
echo modifying keybinds \& settings...
echo
sudo cp settings.json ~/.config/Code/User/
sudo cp keybinds.json ~/.config/COde/User/
echo all settings and keybinds have been configuired...
