#!/bin/bash

echo configuring Visual Studio Code...
echo
echo modifying keybinds \& settings...
echo
sudo cp -r settings.json ~/.config/Code/User/
sudo cp -r keybinds.json ~/.config/COde/User/
echo all settings and keybinds have been configuired...
