#!/bin/bash

a='njpwerner.autodocstring'
b='VisualStudioExptTeam.vscodeintellicode'
c='christian-kohler.path-intellisense'
d='sainnhe.gruvbox-material'
e='oderwat.indent-rainbow'
f='BriteSnow.vscode-toggle-quotes'
g='EditorConfig.EditorConfig'
h='willi84.vikings-icon-theme'
i='miguelsolorio.fluent-icons'
j='usernamehw.errorlens'
k='ms-python.vscode-pylance'
l='ms-python.python'


echo Installing extension $a ...
code --install-extension $a > /dev/null
echo Extension $a was successfully installed...
echo
echo Installing extension $b ...
code --install-extension $b > /dev/null
echo Extension $b was successfully installed...
echo

echo Installing extension $c ...
code --install-extension $c > /dev/null
echo Extension $c was successfully installed...
echo

echo Installing extension $d ...
code --install-extension $d > /dev/null
echo Extension $d was successfully installed...
echo

echo Installing extension $e ...
code --install-extension $e > /dev/null
echo Extension $e was successfully installed...
echo

echo Installing extension $f ...
code --install-extension $f > /dev/null
echo Extension $f was successfully installed...
echo

echo Installing extension $g ...
code --install-extension $g > /dev/null
echo Extension $g was successfully installed...
echo

echo Installing extension $h ...
code --install-extension $h > /dev/null
echo Extension $h was successfully installed...
echo

echo Installing extension $i ...
code --install-extension $i > /dev/null
echo Extension $i was successfully installed...
echo

echo Installing extension $j ...
code --install-extension $j > /dev/null
echo Extension $j was successfully installed...
echo

echo Installing extension $k ...
code --install-extension $k > /dev/null
echo Extension $k was successfully installed...
echo

echo Installing extension $l ...
code --install-extension $l > /dev/null
echo Extension $l was successfully installed...
echo
