#!/bin/bash
echo configuring fish...

echo
echo installing fisher...
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher < /dev/null
echo fisher was successfully installed

echo
echo installing fisher plugins...

echo
echo installing jethrokuan/z...
fisher install jethrokuan/z < /dev/null
echo z was successfully installed...

echo
echo installing jethrokuan/autopair...
fisher install jorgebucaran/autopair.fish < /dev/null
echo jethrokuan/autopair was successfully installed...

echo
echo installing IlanCosman/tide...
yes n | fisher install IlanCosman/tide < /dev/null
echo IlanCosman/tide was successfully installed...

echo
echo note : run 'tide configure' after installation
echo fish was successfully configured...
